### ISSUE TITLE
HDF5 libraries are required on OS

### ISSUE THREAD

**Issue by rue-a** [pangaea-data-publisher/pangaeapy#40]
Since HDF5 libraries are required for the package (see pip error below), it would make sense to add this information to the README. I think it would also be reasonable to add some information on how to install these libraries. For Ubuntu, I found the command pretty quick (`sudo apt-get install libhdf5-serial-dev netcdf-bin libnetcdf-dev`), but maybe it's more complicated for other OS.

Cheers

```pip install pangaeapy
Defaulting to user installation because normal site-packages is not writeable
Collecting pangaeapy
  Downloading pangaeapy-1.0.13-py3-none-any.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 5.4 MB/s eta 0:00:00
Requirement already satisfied: lxml>=4.9.1 in /home/ruemmler/.local/lib/python3.11/site-packages (from pangaeapy) (4.9.2)
Requirement already satisfied: requests>=2.26.0 in /home/ruemmler/.local/lib/python3.11/site-packages (from pangaeapy) (2.28.2)
Requirement already satisfied: pandas>=1.3.5 in /home/ruemmler/.local/lib/python3.11/site-packages (from pangaeapy) (1.5.3)
Requirement already satisfied: numpy>=1.21.0 in /home/ruemmler/.local/lib/python3.11/site-packages (from pangaeapy) (1.23.5)
Collecting netcdf4~=1.5.6
  Downloading netCDF4-1.5.8.tar.gz (767 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.0/767.0 kB 17.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Package hdf5 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `hdf5.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'hdf5' found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-rj5wrjo3/netcdf4_55387b07616a42cd9e4ebf580deadf8c/setup.py", line 419, in <module>
          _populate_hdf5_info(dirstosearch, inc_dirs, libs, lib_dirs)
        File "/tmp/pip-install-rj5wrjo3/netcdf4_55387b07616a42cd9e4ebf580deadf8c/setup.py", line 360, in _populate_hdf5_info
          raise ValueError('did not find HDF5 headers')
      ValueError: did not find HDF5 headers
      reading from setup.cfg...
      
          HDF5_DIR environment variable not set, checking some standard locations ..
      checking /home/ruemmler/include ...
      hdf5 headers not found in /home/ruemmler/include
      checking /usr/local/include ...
      hdf5 headers not found in /usr/local/include
      checking /sw/include ...
      hdf5 headers not found in /sw/include
      checking /opt/include ...
      hdf5 headers not found in /opt/include
      checking /opt/local/include ...
      hdf5 headers not found in /opt/local/include
      checking /usr/include ...
      hdf5 headers not found in /usr/include
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.```

**Comment by huberrob** [comment]
fixes in 1.0.14
